export const wrapper: string;
export const title: string;
export const searchBoxInput: string;
export const searchBoxInputSmall: string;
export const search__results: string;
export const searchResults: string;
export const isHighlighted: string;
export const searchButton: string;
export const searchButtonSmall: string;
