<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function covid_theme($existing, $type, $theme, $path) {
  return [
    'user_login_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_entity_base_field_info().
 */
function covid_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    $fields = [];

    $fields['content'] = BaseFieldDefinition::create('text_long')
      ->setLabel(t('Content'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\covid\NodeComputedContent')
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'above',
        'weight' => -5,
      ]);

    return $fields;
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for node entities.
 */
function covid_node_presave(NodeInterface $entity) {
  // Parse FAQ into questions and answers.
  if ($entity->hasField('field_faq_parser')
    && $entity->hasField('field_questions_answers')
  ) {
    // Only if parser field contains a value.
    if (!empty($value = $entity->get('field_faq_parser')->value)) {
      $values = $entity->get('field_questions_answers')->getValue();

      // Parse all questions and answers from the field value.
      foreach (explode(PHP_EOL, trim($value)) as $line) {
        [$question, $answer] = explode('?', $line, 2);
        // Append parsed values to the existing.
        $values[] = [
          'question' => trim($question) . '?',
          'value' => trim($answer),
        ];
      }
      // Save new values and clear the parser field.
      $entity->set('field_questions_answers', $values);
      $entity->set('field_faq_parser', NULL);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function covid_taxonomy_term_update(EntityInterface $entity) {
  if ($entity->bundle() === 'region') {
    $query = Drupal::entityTypeManager()->getStorage('node')->getQuery();

    $query->condition('type', 'situation');

    $result = $query->execute();

    $tags = array_map(function($id) {
      return 'node:' . $id;
    }, $result ?? []);

    Cache::invalidateTags($tags);
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function covid_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
  /** @var NodeInterface $entity */
  // If node is already published, then allow only admins to delete it.
  if ($operation === 'delete' && !in_array('administrator', $account->getRoles()) && $entity->isPublished()) {
    // Check if any previous revision has been published, we want to restrict access in that case as well.
    $nodeStorage = \Drupal::entityTypeManager()->getStorage('node');
    $revisionIds = $nodeStorage->revisionIds($entity);
    foreach ($revisionIds as $revisionId) {
      /** @var NodeInterface $revision */
      $revision = $nodeStorage->loadRevision($revisionId);
      if ($revision->isPublished()) {
        return AccessResult::forbidden()
          ->cachePerPermissions()
          ->cachePerUser();
      }
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_operation_alter().
 */
function covid_entity_operation_alter(array &$operations, EntityInterface $entity) {
  $roles = Drupal::currentUser()->getRoles();

  $isTranslator = in_array('translator', $roles) && count($roles) === 2;

  // Don't let translator edit nodes (or at least don't show the button).
  // The permission is necessary for translating paragraphs.
  if ($entity->getEntityTypeId() === 'node' && $isTranslator) {
    unset($operations['edit']);
  }
}

/**
 * Implements hook_editor_js_settings_alter
 */
function covid_editor_js_settings_alter(array &$settings) {
  foreach ($settings['editor']['formats'] as $name => $value) {
    $settings['editor']['formats'][$name]['editorSettings']['disableNativeSpellChecker'] = FALSE;
    $settings['editor']['formats'][$name]['editorSettings']['removePlugins'] = 'liststyle,tabletools,scayt,menubutton,contextmenu,tableresize';
    $settings['editor']['formats'][$name]['editorSettings']['browserContextMenuOnCtrl'] = FALSE;
  }
}
