version: '3'
services:

  drupal:
    user: "${COVID_USER}"
    image:  covid_php
    env_file:
      - .env
    volumes:  [ "${COVID_PROJECT_DIR}:/var/www/html:delegated" ]
    build:
      context: .
      dockerfile: Dockerfile.php
    links:
      - database
    depends_on:
      - database

  nginx:
    user: "${COVID_USER}"
    image:  covid_nginx
    ports: [ "${COVID_PORT_NGINX}:8080" ]
    volumes:  [ "${COVID_PROJECT_DIR}:/var/www/html:delegated" ]
    build:
      context: .
      dockerfile: Dockerfile.nginx

  database:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    ports: [ "${COVID_PORT_MSSQL}:1433" ]
    command: /opt/mssql/bin/sqlservr
    environment:
      ACCEPT_EULA: 'Y'
      PATH: >-
        /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/mssql-tools/bin
      SA_PASSWORD: SuperDrupalSite8

