name: "Static build"
on: [workflow_dispatch]

jobs:
  build:
    name: Deploy Gatsby

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: enriikke/gatsby-gh-pages-action@v2
        working-directory: "gatsby"
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: "gh-pages"

